### ISSUE TITLE
todo for wlroots 0.18

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#1260]
- [x] Don't restack unmanaged xwayland surfaces. They are now [asserted against](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4052)
- [x] No more `wlr_output->pending` and `wlr_output_set_foo(wlr_output, bar)`. We now have to roll our [own state](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4202)
- [ ] List of [breaking changes](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3760)
