### ISSUE TITLE
Button TODO

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#1297]
Titlebar button TODO

Re: #1280

- [x] Fix bug where previous alt_filename is carried over (#1290)
- [ ] Refactor to get rid of new `ssd_hover_state` variables `maximized`+`old_node` (#1289)
- [ ] Use better fallback hierarchy where there are missing icons. It's likely that `max`, `iconify`, `close` and `menu` will need to fallback on to built-in xbm arrays, but `foo_hover`, `foo_toggled`, etc should probably fallback onto the `foo` buffers.
- [ ] Refactor xbm fallbacks... consider passing less arguments to `button_xbm_load()`, and possibly have a dedicated function to load the builtin mask if not file exists.
- [ ] Add button overlay (probably best implemented by adding it directly to the buffers) if hover icons does not exist (could make this optional, but is would be a good default option - and avoid regression).
- [ ] Try to remove `struct ssd_hover_state` all together by a pointer-to-a-pointer `**icon` which we just point to `&normal`, `&toggled`, `&hover`, `&toggled_hover` in response to cursor movement.
- [ ] Try to remove code duplications in `button_xbm_load(). https://github.com/labwc/labwc/blob/02aa000b0db211dc3ff5aae6064342008d749b23/src/button/button-xbm.c#L286-L294
- [ ] Update documentations (make `toggled_hover` the de facto and `hover_toggled` the fallback)
- [ ] Revert max_hover_toggled svg/png support. Openbox does not support png/svg so there is no need to support backward compatibility with `max_hover_toggled-{active,inactive}.{png,svg}`
- [ ] Consider `s/restore/max_toggled/` in `theme.c` for consistency.
- [ ] Support foo_pressed.xbm

**Comment by Consolatis** [comment]
This seems mostly done (other than the "For later" section). Can we remove it form the 0.7.0 milestone?

**Comment by johanmalm** [comment]
> This seems mostly done (other than the "For later" section). Can we remove it from the 0.7.0 milestone?

Yes
