### ISSUE TITLE
OSD Improvements #2

### ISSUE THREAD

**Issue by johanmalm** [labwc/labwc#968]
This relates to #879 #893 - but I'm just creating a new issue so that I can control the original post.

- [x] item height based on font height #893
- [x] window switcher width #893
- [x] item vertical padding #893
- [x] focused item border width #893
- [ ] focused item background and text color
- [x] possible to hide each of 3 columns
- [ ] position of desktop name (top/bottom)
- [ ] different font size for desktop switcher and window switcher
- [ ] size of the squares in desktop switcher
- [ ] Consider allowing window-switcher width to be specified as a percentage of output width
- [ ] osd.c: simplify the get_title() helper and associated `is_title_different()`
- [ ] Cope with `nr_items` * `item_height` > `output_height`
- [ ] Show always on-top windows in window-switcher
- [ ] Consider showing multiple work-spaces in window-switcher 
- [ ] Consider showing window thumbnails

**Comment by Consolatis** [comment]
focused item border width doesn't seem to be implemented?

**Comment by stefonarch** [comment]
I'll drop just my 2 cents here: I do not much like the square border of the selected item - why not use the same hover color as in window title menu selected items? Or an option to disable for it?

**Comment by Consolatis** [comment]
We can allow for that when the three new settings are implemented:
- `focused.border.width: 0` (or `focused.thickness` or whatever else we come up with)
- `focused.bg.color: #whatever`
- `focused.text.color: #whatever`

**Comment by droc12345** [comment]
> Consider showing multiple work-spaces in window-switcher

should be checked?

**Comment by droc12345** [comment]
Consolatis, did you want me to fix the rest of the custom config for window switcher?
I think basically it needs doc (which I don't have a problem doing) and removing a few things from
your patch that have already been applied to labwc, ie repackage what you have in the patch.
I know you pointed to a few possible enhancements/fixes, but those could be done after merge 
as fine tuning the code.

I've been using it as my daily way to use window switcher, been working well. 
Putting it in would allow others to start testing it also.

**Comment by Consolatis** [comment]
> Consolatis, did you want me to fix the rest of the custom config for window switcher? I think basically it needs doc (which I don't have a problem doing) and removing a few things from your patch that have already been applied to labwc, ie repackage what you have in the patch.

If you have the time and motivation to do so, feel free :)
Got side tracked, too many things to work on simultaneously.

**Comment by droc12345** [comment]
I knew you were busy, thus the offer 

#1654

**Comment by Vladimir-csp** [comment]
Please also consider adding ability to theme window focus highlight frame, potentially into something other than 3-pixel 2-color frame.

**Comment by xi** [comment]
>  Consider showing window thumbnails

Implemented in #2981.
